// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaBiblioteca.Data;

#nullable disable

namespace SistemaBiblioteca.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20251116205502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutorHemerotecaDocumento", b =>
                {
                    b.Property<int>("AutoresAutorId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentosDocumentoID")
                        .HasColumnType("int");

                    b.HasKey("AutoresAutorId", "DocumentosDocumentoID");

                    b.HasIndex("DocumentosDocumentoID");

                    b.ToTable("AutorHemerotecaDocumento");
                });

            modelBuilder.Entity("AutorLibro", b =>
                {
                    b.Property<int>("AutoresAutorId")
                        .HasColumnType("int");

                    b.Property<int>("LibrosLibroID")
                        .HasColumnType("int");

                    b.HasKey("AutoresAutorId", "LibrosLibroID");

                    b.HasIndex("LibrosLibroID");

                    b.ToTable("AutorLibro");
                });

            modelBuilder.Entity("CategoriaLibro", b =>
                {
                    b.Property<int>("CategoriasCategoriaID")
                        .HasColumnType("int");

                    b.Property<int>("LibrosLibroID")
                        .HasColumnType("int");

                    b.HasKey("CategoriasCategoriaID", "LibrosLibroID");

                    b.HasIndex("LibrosLibroID");

                    b.ToTable("CategoriaLibro");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Autor", b =>
                {
                    b.Property<int>("AutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutorId"));

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutorId");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Bibliotecario", b =>
                {
                    b.Property<int>("BibliotecarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BibliotecarioID"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioBibliotecario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BibliotecarioID");

                    b.ToTable("Bibliotecarios");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Carnet", b =>
                {
                    b.Property<int>("CarnetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarnetID"));

                    b.Property<string>("CodigoCarnet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("LectorID")
                        .HasColumnType("int");

                    b.HasKey("CarnetID");

                    b.HasIndex("LectorID")
                        .IsUnique();

                    b.ToTable("Carnets");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Categoria", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Ejemplar", b =>
                {
                    b.Property<int>("EjemplarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjemplarID"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LibroID")
                        .HasColumnType("int");

                    b.Property<string>("TipoAdquisicion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EjemplarID");

                    b.HasIndex("LibroID");

                    b.ToTable("Ejemplares");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.EscuelaProfesional", b =>
                {
                    b.Property<int>("EscuelaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EscuelaID"));

                    b.Property<int>("FacultadID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EscuelaID");

                    b.HasIndex("FacultadID");

                    b.ToTable("EscuelasProfesionales");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Facultad", b =>
                {
                    b.Property<int>("FacultadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultadId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacultadId");

                    b.ToTable("Facultades");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.HemerotecaConsulta", b =>
                {
                    b.Property<int>("ConsultaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultaID"));

                    b.Property<int>("DocumentoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("HemerotecaDocumentoDocumentoID")
                        .HasColumnType("int");

                    b.Property<int>("LectorID")
                        .HasColumnType("int");

                    b.HasKey("ConsultaID");

                    b.HasIndex("HemerotecaDocumentoDocumentoID");

                    b.HasIndex("LectorID");

                    b.ToTable("HemerotecaConsultas");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.HemerotecaDocumento", b =>
                {
                    b.Property<int>("DocumentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentoID"));

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentoID");

                    b.ToTable("HemerotecaDocumentos");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Incidencia", b =>
                {
                    b.Property<int>("IncidenciaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidenciaID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EjemplarID")
                        .HasColumnType("int");

                    b.Property<string>("EstadoIncidencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<int>("LectorID")
                        .HasColumnType("int");

                    b.Property<int?>("PrestamoID")
                        .HasColumnType("int");

                    b.Property<string>("TipoSancion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidenciaID");

                    b.HasIndex("EjemplarID");

                    b.HasIndex("LectorID");

                    b.HasIndex("PrestamoID");

                    b.ToTable("Incidencias");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Lector", b =>
                {
                    b.Property<int>("LectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LectorID"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoEstudiante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EscuelaID")
                        .HasColumnType("int");

                    b.Property<int?>("EscuelaProfesionalEscuelaID")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoLectorID")
                        .HasColumnType("int");

                    b.HasKey("LectorID");

                    b.HasIndex("EscuelaProfesionalEscuelaID");

                    b.HasIndex("TipoLectorID");

                    b.ToTable("Lectores");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Libro", b =>
                {
                    b.Property<int>("LibroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LibroID"));

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("Edicion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumEstanteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumPaginas")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LibroID");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Prestamo", b =>
                {
                    b.Property<int>("PrestamoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoID"));

                    b.Property<int>("BibliotecarioID")
                        .HasColumnType("int");

                    b.Property<int>("EjemplarID")
                        .HasColumnType("int");

                    b.Property<string>("EstadoPrestamo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDevolucionPrevista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucionReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime2");

                    b.Property<int>("LectorID")
                        .HasColumnType("int");

                    b.HasKey("PrestamoID");

                    b.HasIndex("BibliotecarioID");

                    b.HasIndex("EjemplarID");

                    b.HasIndex("LectorID");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.TipoLector", b =>
                {
                    b.Property<int>("TipoLectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoLectorID"));

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoLectorID");

                    b.ToTable("TiposLectores");
                });

            modelBuilder.Entity("AutorHemerotecaDocumento", b =>
                {
                    b.HasOne("SistemaBiblioteca.Modelos.Autor", null)
                        .WithMany()
                        .HasForeignKey("AutoresAutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBiblioteca.Modelos.HemerotecaDocumento", null)
                        .WithMany()
                        .HasForeignKey("DocumentosDocumentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutorLibro", b =>
                {
                    b.HasOne("SistemaBiblioteca.Modelos.Autor", null)
                        .WithMany()
                        .HasForeignKey("AutoresAutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBiblioteca.Modelos.Libro", null)
                        .WithMany()
                        .HasForeignKey("LibrosLibroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CategoriaLibro", b =>
                {
                    b.HasOne("SistemaBiblioteca.Modelos.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasCategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBiblioteca.Modelos.Libro", null)
                        .WithMany()
                        .HasForeignKey("LibrosLibroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Carnet", b =>
                {
                    b.HasOne("SistemaBiblioteca.Modelos.Lector", "Lector")
                        .WithOne("Carnet")
                        .HasForeignKey("SistemaBiblioteca.Modelos.Carnet", "LectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lector");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Ejemplar", b =>
                {
                    b.HasOne("SistemaBiblioteca.Modelos.Libro", "Libro")
                        .WithMany("Ejemplares")
                        .HasForeignKey("LibroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.EscuelaProfesional", b =>
                {
                    b.HasOne("SistemaBiblioteca.Modelos.Facultad", "Facultad")
                        .WithMany("EscuelasProfesionales")
                        .HasForeignKey("FacultadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.HemerotecaConsulta", b =>
                {
                    b.HasOne("SistemaBiblioteca.Modelos.HemerotecaDocumento", "HemerotecaDocumento")
                        .WithMany("HemerotecaConsultas")
                        .HasForeignKey("HemerotecaDocumentoDocumentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBiblioteca.Modelos.Lector", "Lector")
                        .WithMany("HemerotecaConsultas")
                        .HasForeignKey("LectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HemerotecaDocumento");

                    b.Navigation("Lector");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Incidencia", b =>
                {
                    b.HasOne("SistemaBiblioteca.Modelos.Ejemplar", "Ejemplar")
                        .WithMany("Incidencias")
                        .HasForeignKey("EjemplarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBiblioteca.Modelos.Lector", "Lector")
                        .WithMany("Incidencias")
                        .HasForeignKey("LectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBiblioteca.Modelos.Prestamo", "Prestamo")
                        .WithMany("Incidencias")
                        .HasForeignKey("PrestamoID");

                    b.Navigation("Ejemplar");

                    b.Navigation("Lector");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Lector", b =>
                {
                    b.HasOne("SistemaBiblioteca.Modelos.EscuelaProfesional", "EscuelaProfesional")
                        .WithMany()
                        .HasForeignKey("EscuelaProfesionalEscuelaID");

                    b.HasOne("SistemaBiblioteca.Modelos.TipoLector", "TipoLector")
                        .WithMany("Lectores")
                        .HasForeignKey("TipoLectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EscuelaProfesional");

                    b.Navigation("TipoLector");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Prestamo", b =>
                {
                    b.HasOne("SistemaBiblioteca.Modelos.Bibliotecario", "Bibliotecario")
                        .WithMany("Prestamos")
                        .HasForeignKey("BibliotecarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBiblioteca.Modelos.Ejemplar", "Ejemplar")
                        .WithMany("Prestamos")
                        .HasForeignKey("EjemplarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaBiblioteca.Modelos.Lector", "Lector")
                        .WithMany("Prestamos")
                        .HasForeignKey("LectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bibliotecario");

                    b.Navigation("Ejemplar");

                    b.Navigation("Lector");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Bibliotecario", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Ejemplar", b =>
                {
                    b.Navigation("Incidencias");

                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Facultad", b =>
                {
                    b.Navigation("EscuelasProfesionales");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.HemerotecaDocumento", b =>
                {
                    b.Navigation("HemerotecaConsultas");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Lector", b =>
                {
                    b.Navigation("Carnet");

                    b.Navigation("HemerotecaConsultas");

                    b.Navigation("Incidencias");

                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Libro", b =>
                {
                    b.Navigation("Ejemplares");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.Prestamo", b =>
                {
                    b.Navigation("Incidencias");
                });

            modelBuilder.Entity("SistemaBiblioteca.Modelos.TipoLector", b =>
                {
                    b.Navigation("Lectores");
                });
#pragma warning restore 612, 618
        }
    }
}
